import jsonpath

depend_response = {'success': 'success', 'message': '&#25552;&#20132;&#25104;&#21151;', 'detailMsg': {'data': [
    {'id': '0SpXPBkHrhrlUDXKnbt9', 'dr': 0, 'ts': 1589178838139, 'creator': 'smq', 'creationTime': 1589178835000,
     'modifier': 'smq', 'modifiedTime': 1589178838139, 'persistStatus': 'upd', 'promptMessage': None, 'state': 1,
     'approver': 'smq', 'approveTime': 1589178838139, 'approveOpinion': None, 'sycnNCStatus': None,
     'sycnOutStatus': None, 'pkOrgId': 'abd7cf79-511d-4307-9bbd-d288b18d0ef9', 'pkOrgCode': '1210',
     'pkOrgName': '西安喜马拉雅网络科技有限公司', 'pkOrgInId': 'abd7cf79-511d-4307-9bbd-d288b18d0ef9', 'pkOrgInCode': '1210',
     'pkOrgInName': '西安喜马拉雅网络科技有限公司', 'code': 'DBO20200511000007', 'billDate': 1585238400000, 'billType': 'Allocation',
     'billTranTypeId': 'Allocation', 'billTranTypeCode': 'Allocation', 'billTranTypeName': '调拨单',
     'outStorageId': '1001ZZ100000000DPAP4', 'outStorageCode': 'test030201', 'outStorageName': '测试仓库030201',
     'outIfSlotManage': None, 'inStorageId': '1001ZZ100000000DPAP6', 'inStorageCode': 'test030202',
     'inStorageName': 'test030202', 'inIfSlotManage': None, 'outBizPersonId': '0mWG6nOSCxjsi1zoKEYs',
     'outBizPersonCode': '007', 'outBizPersonName': '师孟奇', 'inBizPersonId': '0wsjdHVUBFlca3pyH155',
     'inBizPersonCode': '2539', 'inBizPersonName': '唐林', 'outDeptId': 'ae96b9ed-82dc-4aa7-bf97-cdd18a18c1a9',
     'outDeptCode': '01010102', 'outDeptName': '城市经理', 'inDeptId': '02f265b0-aca6-4364-bd1b-50de07ef9482',
     'inDeptCode': '02', 'inDeptName': '中台&业务支撑', 'planSendDate': None, 'planArriveDate': None,
     'currencyId': 'CURRENCY-01', 'currencyCode': 'RMB', 'currencyName': '人民币', 'totalFactOutNum': None,
     'totalFactInNum': None, 'billStatusId': None, 'billStatusCode': None, 'billStatusName': None,
     'transferStatusId': '0s21f51f-4f42-4100-dkd0-3254fbq33e6k', 'transferStatusCode': '1', 'transferStatusName': '待处理',
     'stockBillBelong': None, 'customerId': None, 'customerName': None, 'customerCode': None, 'isClose': 0,
     'closer': None, 'closeDate': None, 'closeReason': None, 'remark': '自动化测试新增调拨单', 'transferBillItems': [
        {'id': '0nfvSk3qPUdDm3BsCDdI', 'dr': 0, 'ts': 1589178837000, 'creator': 'smq', 'creationTime': 1589178837000,
         'modifier': None, 'modifiedTime': None, 'persistStatus': 'nrm', 'promptMessage': None, 'rowNum': 10,
         'transferBillId': '0SpXPBkHrhrlUDXKnbt9', 'goodsId': '03e77ae0-469d-4d8a-ba34-733c2ada3749',
         'goodsCode': '301020000049', 'goodsName': '小雅AI音箱旗舰版_石墨绿', 'goodsFullName': None, 'goodsBasicUnitName': '个',
         'goodsAssistUnitName': '个', 'goodsConversionRate': 1.0, 'enableBatchNumberManage': None, 'productId': None,
         'productLineId': None, 'isOptional': None, 'unitId': 'UNIT-12', 'unitCode': 'EA', 'unitName': '个',
         'transferNum': 5.0, 'onwayNum': None, 'totalOutNum': None, 'totalInNum': None, 'unitPrice': None,
         'amountMoney': 0.0, 'remark': None, 'batchNumId': None, 'batchNumCode': None, 'batchNumName': None,
         'goodsPositionId': None, 'goodsPositionCode': None, 'goodsPositionName': None, 'receiverAddress': None,
         'provinceId': None, 'provinceCode': None, 'provinceName': None, 'cityId': None, 'cityCode': None,
         'cityName': None, 'countyId': None, 'countyCode': None, 'countyName': None, 'townId': None, 'townCode': None,
         'townName': None, 'detailAddr': None, 'receiver': None, 'receiverPhone': None, 'receiverPhoneSpare': None,
         'isClose': 0, 'sourceId': None, 'sourceLineNum': None, 'sourceType': None, 'ext01': None, 'ext02': None,
         'ext03': None, 'ext04': None, 'ext05': None, 'ext06': None, 'ext07': None, 'ext08': None, 'ext09': None,
         'ext10': None, 'ext11': None, 'ext12': None, 'ext13': None, 'ext14': None, 'ext15': None, 'goodsVersion': '1',
         'goodsSelection': None, 'isMotherPiece': None, 'customerId': None, 'customerCode': None, 'customerName': None,
         'supplierId': None, 'supplierCode': None, 'supplierName': None, 'projectId': None, 'projectCode': None,
         'projectName': None, 'batchCodeId': None, 'batchCodeCode': None, 'stockStateId': None, 'stockStateCode': None,
         'stockStateName': None, 'enableBatchNoManage': None, 'enableInvStatusManage': None, 'originalGoodsId': None,
         'goodsSelectionDescription': None, 'outStorageId': '1001ZZ100000000DPAP4', 'outStorageCode': 'test030201',
         'outStorageName': '测试仓库030201', 'outIfSlotManage': None, 'inStorageId': '1001ZZ100000000DPAP6',
         'inStorageCode': 'test030202', 'inStorageName': 'test030202', 'inIfSlotManage': None, 'outPositionId': None,
         'outPositionCode': None, 'outPositionName': None}], 'transferBillItemBoms': [
        {'id': '0azTCvC3kzK4PPG1H25I', 'dr': 0, 'ts': 1589178837000, 'creator': 'smq', 'creationTime': 1589178837000,
         'modifier': None, 'modifiedTime': None, 'persistStatus': 'nrm', 'promptMessage': None, 'rowNum': '10',
         'goodsId': '03e77ae0-469d-4d8a-ba34-733c2ada3749', 'goodsCode': '301020000049', 'goodsName': '小雅AI音箱旗舰版_石墨绿',
         'goodsFullName': None, 'goodsBasicUnitName': '个', 'goodsAssistUnitName': '个', 'goodsConversionRate': 1.0,
         'enableBatchNumberManage': None, 'productId': None, 'productLineId': None, 'unitId': 'UNIT-12',
         'unitCode': 'EA', 'unitName': '个', 'transferNum': 5.0, 'onwayNum': None, 'totalOutNum': None,
         'totalInNum': None, 'unitPrice': None, 'amountMoney': 0.0, 'remark': None, 'batchNumId': None,
         'batchNumCode': None, 'batchNumName': None, 'goodsPositionId': None, 'goodsPositionCode': None,
         'goodsPositionName': None, 'receiverAddress': None, 'provinceId': None, 'provinceCode': None,
         'provinceName': None, 'cityId': None, 'cityCode': None, 'cityName': None, 'countyId': None, 'countyCode': None,
         'countyName': None, 'townId': None, 'townCode': None, 'townName': None, 'detailAddr': None, 'receiver': None,
         'receiverPhone': None, 'receiverPhoneSpare': None, 'isClose': 0, 'sourceId': None, 'sourceLineNum': None,
         'sourceType': None, 'ext01': None, 'ext02': None, 'ext03': None, 'ext04': None, 'ext05': None, 'ext06': None,
         'ext07': None, 'ext08': None, 'ext09': None, 'ext10': None, 'ext11': None, 'ext12': None, 'ext13': None,
         'ext14': None, 'ext15': None, 'goodsVersion': '1', 'goodsSelection': None, 'customerId': None,
         'customerCode': None, 'customerName': None, 'supplierId': None, 'supplierCode': None, 'supplierName': None,
         'projectId': None, 'projectCode': None, 'projectName': None, 'batchCodeId': None, 'batchCodeCode': None,
         'stockStateId': None, 'stockStateCode': None, 'stockStateName': None, 'originalGoodsId': None,
         'goodsSelectionDescription': None, 'itemId': '0nfvSk3qPUdDm3BsCDdI', 'billId': '0SpXPBkHrhrlUDXKnbt9',
         'parentGoodsId': '03e77ae0-469d-4d8a-ba34-733c2ada3749', 'parentGoodsCode': '301020000049',
         'parentGoodsName': '小雅AI音箱旗舰版_石墨绿', 'parentGoodsdisplayName': None, 'parentRowNum': '10',
         'childGoodsQty': None, 'firstBillBomCode': None, 'srcBillBomCode': None,
         'outStorageId': '1001ZZ100000000DPAP4', 'outStorageCode': 'test030201', 'outStorageName': '测试仓库030201',
         'outIfSlotManage': None, 'inStorageId': '1001ZZ100000000DPAP6', 'inStorageCode': 'test030202',
         'inStorageName': 'test030202', 'inIfSlotManage': None, 'outPositionId': None, 'outPositionCode': None,
         'outPositionName': None}], 'ext01': None, 'ext02': None, 'ext03': None, 'ext04': None, 'ext05': None,
     'ext06': None, 'ext07': None, 'ext08': None, 'ext09': None, 'ext10': None, 'ext11': None, 'ext12': None,
     'ext13': None, 'ext14': None, 'ext15': None, 'isDistribution': None, 'isReturned': None}]}}

re = jsonpath.jsonpath(depend_response, '$..%s' %'id')[0]
print(re)
